# Generated by Django 4.1.7 on 2023-03-22 14:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="albums",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("album_name", models.CharField(max_length=100)),
                ("album_spotify_idx", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="artists",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("artist_name", models.CharField(max_length=100)),
                ("album_spotify_idx", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="tracks",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("track_spotify_idx", models.CharField(max_length=200)),
                ("track_name", models.CharField(max_length=200)),
                ("lyrics", models.TextField()),
            ],
        ),
    ]
