# Generated by Django 4.1.7 on 2023-03-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="albums", old_name="id", new_name="_id",),
        migrations.RenameField(model_name="artists", old_name="id", new_name="_id",),
        migrations.RenameField(model_name="tracks", old_name="id", new_name="_id",),
    ]
